services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: deploy/docker/Dockerfile.dev
    volumes:
      - ./frontend/src:/code/src/
      - ./frontend/public:/code/public/
      - /code/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    container_name: backend
    build:
      context: ./backend/api-server/
      dockerfile: ../deploy/docker/Dockerfile.dev
    volumes:
      - ./backend/api-server:/code/
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DEPLOYMENT_ENVIRONMENT=dev

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./proxy/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "10000:10000"
    depends_on:
      - frontend
      - backend

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"