services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: deploy/docker/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    container_name: backend
    build:
      context: ./backend/api-server/
      dockerfile: ../deploy/docker/Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - /home/ec2-user/habits/.env

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./proxy/nginx-prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"