# Used in development
FROM python:3.12

WORKDIR /code/
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install debugpy
COPY . .
EXPOSE 8000
EXPOSE 5678

CMD ["sh", "-c", "python manage.py migrate && python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
