# Stage 1: Build stage
FROM node:18 AS builder

WORKDIR /code/
COPY package*.json ./
RUN npm install
COPY ./src ./src
COPY ./public ./public
RUN npm run build

# Stage 2: Production stage
FROM nginx:alpine

COPY --from=builder /code/build /usr/share/nginx/html
COPY ./deploy/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]