name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd habits/
          git pull origin main
          cd ec2/
          sudo cp ./docker-compose.service /etc/systemd/system/docker-compose.service
          sudo systemctl daemon-reload
          sudo systemctl enable docker-compose
          sudo systemctl start docker-compose
        EOF
