name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd habits/
          git pull origin main

          # Create or update the .env file
          echo "RDS_DB_NAME=${{ secrets.RDS_DB_NAME }}" > .env
          echo "RDS_USERNAME=${{ secrets.RDS_USERNAME }}" >> .env
          echo "RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" >> .env
          echo "RDS_HOSTNAME=${{ secrets.RDS_HOSTNAME }}" >> .env
          echo "RDS_PORT=${{ secrets.RDS_PORT }}" >> .env
          echo "DEPLOYMENT_ENVIRONMENT=prod" >> .env

          cd ec2/
          sudo cp ./docker-compose.service /etc/systemd/system/docker-compose.service
          sudo systemctl daemon-reload
          sudo systemctl enable docker-compose
          sudo systemctl start docker-compose
        EOF
